import { useEffect, useState } from 'react';
import { api, Player, positionName } from '../api';
import '../interactive.css';

export function Research({ onSelect, onCompare, onSquad }: { onSelect: (id: number) => void; onCompare: (id: number) => void; onSquad: () => void }) {
  const [search, setSearch] = useState(''); const [position, setPosition] = useState(''); const [sort, setSort] = useState('form'); const [minPrice, setMinPrice] = useState(''); const [maxPrice, setMaxPrice] = useState(''); const [minForm, setMinForm] = useState(''); const [minMinutes, setMinMinutes] = useState(''); const [viewMode, setViewMode] = useState<'table' | 'cards'>('table'); const [showFilters, setShowFilters] = useState(false); const [players, setPlayers] = useState<Player[]>([]); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { const timer = window.setTimeout(() => { const params = new URLSearchParams({ pageSize: '25', sort, direction: 'desc' }); if (search) params.set('search', search); if (position) params.set('position', position); if (minPrice) params.set('minPrice', minPrice); if (maxPrice) params.set('maxPrice', maxPrice); if (minForm) params.set('minForm', minForm); if (minMinutes) params.set('minMinutes', minMinutes); const cacheKey = `fantasy-helper:players:${params.toString()}`; const cached = window.localStorage.getItem(cacheKey); if (cached) { const saved = JSON.parse(cached) as { items: Player[]; total: number }; setPlayers(saved.items); setTotal(saved.total); setLoading(false); } setLoading(true); api.players(params).then((result) => { setPlayers(result.items); setTotal(result.total); window.localStorage.setItem(cacheKey, JSON.stringify({ items: result.items, total: result.total })); setError(''); }).catch((reason) => setError(reason instanceof Error ? reason.message : 'Could not load players.')).finally(() => setLoading(false)); }, 240); return () => window.clearTimeout(timer); }, [search, position, sort, minPrice, maxPrice, minForm, minMinutes]);
  const clearFilters = () => { setMinPrice(''); setMaxPrice(''); setMinForm(''); setMinMinutes(''); setPosition(''); };
  const playerActions = (player: Player) => <div className="row-actions"><button title="Compare" aria-label="Compare player" onClick={() => onCompare(player.id)}>＋</button><button title="Inspect" aria-label="Inspect player" onClick={() => onSelect(player.id)}>→</button></div>;
  return <section className="page-section"><div className="hero-grid"><div className="hero-copy"><span className="eyebrow accent">RESEARCH DESK</span><h2>Find the edge<br /><em>before deadline.</em></h2><p>Build conviction from form, minutes, fixtures, and value. Every signal stays visible so your decisions remain yours.</p><button className="primary-button" onClick={onSquad}>Open squad planner <span>→</span></button></div><div className="hero-card"><div className="hero-card-top"><span>Decision lens</span><span className="live-pill"><i /> live snapshot</span></div><div className="lens-score">8.4 <span>/ 10</span></div><div className="lens-label">Research readiness</div><div className="signal-bars"><Signal label="Form" value={82} color="green" /><Signal label="Minutes" value={94} color="blue" /><Signal label="Fixtures" value={68} color="orange" /></div><div className="hero-card-footer">18 players worth a closer look <span>↗</span></div></div></div>
    <div className="section-heading"><div><span className="eyebrow">THE PLAYER POOL</span><h3>Research all players <small>{total || 18} tracked</small></h3></div><div className="view-toggle"><button className={viewMode === 'table' ? 'selected' : ''} onClick={() => setViewMode('table')}>▤ Table</button><button className={viewMode === 'cards' ? 'selected' : ''} onClick={() => setViewMode('cards')}>▦ Cards</button></div></div>
    <div className="filter-bar"><div className="search-box"><span>⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by player or club..." /><kbd>⌘ K</kbd></div><select aria-label="Position" value={position} onChange={(event) => setPosition(event.target.value)}><option value="">All positions</option><option value="1">Goalkeepers</option><option value="2">Defenders</option><option value="3">Midfielders</option><option value="4">Forwards</option></select><select aria-label="Sort players" value={sort} onChange={(event) => setSort(event.target.value)}><option value="form">Sort: Form</option><option value="points">Sort: Total points</option><option value="value">Sort: Value</option><option value="minutes">Sort: Minutes</option><option value="price">Sort: Price</option></select><button className="filter-button" onClick={() => setShowFilters(!showFilters)} aria-expanded={showFilters}>＋ Filters</button></div>
    {showFilters && <div className="advanced-filters" data-testid="advanced-filters"><label>Min price<input aria-label="Minimum price" type="number" min="0" step="0.1" value={minPrice} onChange={(event) => setMinPrice(event.target.value)} /></label><label>Max price<input aria-label="Maximum price" type="number" min="0" step="0.1" value={maxPrice} onChange={(event) => setMaxPrice(event.target.value)} /></label><label>Min form<input aria-label="Minimum form" type="number" min="0" step="0.1" value={minForm} onChange={(event) => setMinForm(event.target.value)} /></label><label>Min minutes<input aria-label="Minimum minutes" type="number" min="0" step="1" value={minMinutes} onChange={(event) => setMinMinutes(event.target.value)} /></label><button className="secondary-button" onClick={clearFilters}>Clear filters</button></div>}
    {viewMode === 'table' ? <div className="table-wrap" data-testid="player-table"><table><thead><tr><th>Player</th><th>Pos</th><th>Price</th><th>Form <span className="sort-arrow">↓</span></th><th>Pts</th><th>Min</th><th>Value</th><th>Availability</th><th /></tr></thead><tbody>{loading ? <tr><td colSpan={9} className="table-state">Loading research universe…</td></tr> : error ? <tr><td colSpan={9} className="table-state error-state">{error}</td></tr> : players.length === 0 ? <tr><td colSpan={9} className="table-state">No players match those filters.</td></tr> : players.map((player, index) => <tr key={player.id}><td><button className="player-cell" onClick={() => onSelect(player.id)}><span className={`player-avatar avatar-${index % 5}`}>{player.webName.slice(0, 2).toUpperCase()}</span><span><strong>{player.webName}</strong><small>{['Northbridge', 'Riverside', 'Kingsport', 'Harbour City', 'Old Town'][player.teamId - 1] ?? 'Club'}</small></span></button></td><td><span className="position-tag">{positionName(player.position)}</span></td><td className="mono">£{player.price.toFixed(1)}</td><td><strong className="metric-green">{player.form.toFixed(1)}</strong></td><td className="mono">{player.totalPoints}</td><td className="mono">{player.minutes}</td><td><span className="value-pill">{player.value.toFixed(1)}</span></td><td><span className="availability"><i /> Available</span></td><td>{playerActions(player)}</td></tr>)}</tbody></table></div> : <div className="player-cards" data-testid="player-cards">{loading ? <div className="table-state">Loading research universe…</div> : error ? <div className="table-state error-state">{error}</div> : players.length === 0 ? <div className="table-state">No players match those filters.</div> : players.map((player, index) => <article className="player-card" key={player.id}><button className="player-cell" onClick={() => onSelect(player.id)}><span className={`large-avatar avatar-${index % 5}`}>{player.webName.slice(0, 2).toUpperCase()}</span><span><strong>{player.webName}</strong><small>{positionName(player.position)} · £{player.price.toFixed(1)}</small></span></button><div className="card-metrics"><span>Form <strong>{player.form.toFixed(1)}</strong></span><span>Points <strong>{player.totalPoints}</strong></span><span>Value <strong>{player.value.toFixed(1)}</strong></span></div>{playerActions(player)}</article>)}</div>}
    <div className="table-footer"><span>Showing {players.length} of {total || 18} players</span><div><button disabled aria-label="Previous page">←</button><button className="page-selected" aria-label="Current page" disabled>1</button><button disabled aria-label="Next page">→</button></div></div>
  </section>;
}
function Signal({ label, value, color }: { label: string; value: number; color: string }) { return <div className="signal-row"><span>{label}</span><div className="signal-track"><i className={color} style={{ width: `${value}%` }} /></div><strong>{value}</strong></div>; }
