import { useEffect, useMemo, useState } from 'react';
import { api, DifferentialRow, FixtureResearchRow, PlayerResearchItem, positionName, Squad, TransferSimulation, TransferSimulationInput } from '../api';
import { DataTable, DataTableColumn, DataTableFilters, DataTableSort } from '../components/data-table';

type Tab = 'transfers' | 'fixtures' | 'differentials';

export function TransferResearch({ seasonId, gameweek }: { seasonId: number; gameweek: number }) {
  const [tab, setTab] = useState<Tab>('transfers');
  const [horizon, setHorizon] = useState(5);
  return <section className="transfer-research" data-testid="transfer-research">
    <div className="section-heading"><div><span className="eyebrow accent">DECISION RESEARCH</span><h2>Transfers & fixture swings</h2><p>Model legal moves against deadline-safe warehouse snapshots. Simulations never change your FPL team.</p></div><label className="research-horizon">Horizon<select aria-label="Research horizon" value={horizon} onChange={(event) => setHorizon(Number(event.target.value))}>{[1, 2, 3, 4, 5, 6, 7, 8].map((value) => <option key={value} value={value}>{value} GW{value === 1 ? '' : 's'}</option>)}</select></label></div>
    <div className="research-tabs" role="tablist">{([['transfers', 'Transfer lab'], ['fixtures', 'Fixture swings'], ['differentials', 'Differentials']] as [Tab, string][]).map(([key, label]) => <button role="tab" aria-selected={tab === key} className={tab === key ? 'active' : ''} key={key} onClick={() => setTab(key)}>{label}</button>)}</div>
    {tab === 'transfers' && <TransferLab seasonId={seasonId} gameweek={gameweek} horizon={horizon} />}
    {tab === 'fixtures' && <FixtureTable seasonId={seasonId} gameweek={gameweek} horizon={horizon} />}
    {tab === 'differentials' && <DifferentialTable seasonId={seasonId} gameweek={gameweek} horizon={horizon} />}
  </section>;
}

function TransferLab({ seasonId, gameweek, horizon }: { seasonId: number; gameweek: number; horizon: number }) {
  const [squad, setSquad] = useState<Squad | null>(null);
  const [players, setPlayers] = useState<PlayerResearchItem[]>([]);
  const [draftMoves, setDraftMoves] = useState([{ playerOut: '', playerIn: '' }]);
  const [freeTransfers, setFreeTransfers] = useState(1);
  const [result, setResult] = useState<TransferSimulation | null>(null);
  const [scenarioName, setScenarioName] = useState('');
  const [confirmSave, setConfirmSave] = useState(false);
  const [message, setMessage] = useState('');
  const [busy, setBusy] = useState(false);
  useEffect(() => { const controller = new AbortController(); setResult(null); Promise.all([api.squad(seasonId, controller.signal), api.players(new URLSearchParams({ seasonId: String(seasonId), page: '1', pageSize: '100', sort: 'name', direction: 'asc' }), controller.signal)]).then(([saved, catalogue]) => { setSquad(saved); setPlayers(catalogue.items); setMessage(''); }).catch((error) => { if (!controller.signal.aborted) setMessage(error instanceof Error ? error.message : 'Transfer lab is unavailable.'); }); return () => controller.abort(); }, [seasonId]);
  const selectedOutgoing = new Set(draftMoves.map((move) => Number(move.playerOut)).filter(Boolean));
  const selectedIncoming = new Set(draftMoves.map((move) => Number(move.playerIn)).filter(Boolean));
  const simulation: TransferSimulationInput = { seasonId, gameweek, horizon, freeTransfers, transfers: draftMoves.filter((move) => move.playerOut && move.playerIn).map((move) => ({ playerOut: Number(move.playerOut), playerIn: Number(move.playerIn) })) };
  const movesComplete = draftMoves.every((move) => move.playerOut && move.playerIn);
  const outgoing = squad?.players.find((player) => player.id === Number(draftMoves[0].playerOut));
  const incoming = players.find((item) => item.player.id === Number(draftMoves[0].playerIn))?.player;
  const updateMove = (index: number, field: 'playerOut' | 'playerIn', value: string) => { setDraftMoves((current) => current.map((move, candidate) => candidate === index ? { ...move, [field]: value, ...(field === 'playerOut' ? { playerIn: '' } : {}) } : move)); setResult(null); };
  const reset = () => { setDraftMoves([{ playerOut: '', playerIn: '' }]); setResult(null); setScenarioName(''); setConfirmSave(false); setMessage(''); };
  const run = async () => { setBusy(true); setMessage(''); try { setResult(await api.simulateTransfers(simulation)); } catch (error) { setResult(null); setMessage(error instanceof Error ? error.message : 'Simulation failed.'); } finally { setBusy(false); } };
  if (!squad || squad.players.length !== 15) return <div className="empty-panel compact-empty"><h3>Save a complete squad first</h3><p>The transfer lab starts from your private 15-player planning squad.</p>{message && <span role="alert">{message}</span>}</div>;
  return <div className="transfer-lab">
    <div className="transfer-form"><div className="transfer-moves">{draftMoves.map((move, index) => { const outgoing = squad.players.find((player) => player.id === Number(move.playerOut)); const compatible = players.filter((item) => !squad.purchasePrices[item.player.id] && !selectedIncoming.has(item.player.id) && (!outgoing || item.player.position === outgoing.position)); return <div className="transfer-move" key={index}><label>Transfer out {index + 1}<select aria-label={`Transfer out ${index + 1}`} value={move.playerOut} onChange={(event) => updateMove(index, 'playerOut', event.target.value)}><option value="">Choose owned player</option>{squad.players.filter((player) => player.id === Number(move.playerOut) || !selectedOutgoing.has(player.id)).map((player) => <option value={player.id} key={player.id}>{player.webName} · {positionName(player.position)} · £{player.price.toFixed(1)}</option>)}</select></label><span className="transfer-arrow">→</span><label>Transfer in {index + 1}<select aria-label={`Transfer in ${index + 1}`} value={move.playerIn} disabled={!move.playerOut} onChange={(event) => updateMove(index, 'playerIn', event.target.value)}><option value="">Choose replacement</option>{compatible.map(({ player }) => <option value={player.id} key={player.id}>{player.webName} · £{player.price.toFixed(1)}</option>)}</select></label>{draftMoves.length > 1 && <button className="text-button remove-transfer" aria-label={`Remove transfer ${index + 1}`} onClick={() => { setDraftMoves((current) => current.filter((_, candidate) => candidate !== index)); setResult(null); }}>Remove</button>}</div>; })}<button className="text-button add-transfer" disabled={draftMoves.length >= 5} onClick={() => setDraftMoves((current) => [...current, { playerOut: '', playerIn: '' }])}>Add another transfer</button></div><label>Free transfers<input aria-label="Free transfers" type="number" min="0" max="5" value={freeTransfers} onChange={(event) => setFreeTransfers(Number(event.target.value))} /></label><div className="button-row"><button className="primary-button" disabled={busy || !movesComplete} onClick={() => void run()}>{busy ? 'Calculating…' : 'Calculate moves'}</button><button className="text-button" onClick={reset}>Reset</button></div></div>
    {message && <div className="inline-error" role="alert">{message}</div>}
    {result && <article className="simulation-result" data-testid="simulation-result"><div><span className="eyebrow">SIMULATION {result.simulationId}</span><h3>{outgoing?.webName} → {incoming?.webName}</h3><p>Read-only result from snapshot {result.snapshotId}. {result.state !== 'actual' ? `Data state: ${result.state}.` : ''}</p></div><div className="simulation-metrics"><Metric label="Bank after" value={`£${result.after.remainingBudget.toFixed(1)}`} /><Metric label="Point hit" value={`−${result.pointsHit}`} warning={result.pointsHit > 0} /><Metric label="Fixture ease" value={`${signed(result.fixtureEaseDelta)}`} /><Metric label="Paid moves" value={String(result.paidTransfers)} /></div><details><summary>Assumptions and provenance</summary><p>{result.assumptions.join(' ')}</p><p>Formulae: {result.formulaVersions.join(', ')} · observed {new Date(result.observedAt).toLocaleString()}</p></details><div className="scenario-save"><label>Scenario name<input aria-label="Scenario name" value={scenarioName} maxLength={100} onChange={(event) => { setScenarioName(event.target.value); setConfirmSave(false); }} placeholder="e.g. Attack GW 4–8" /></label>{confirmSave ? <div className="save-confirmation" role="alert"><span>Save this immutable scenario? Your active squad stays unchanged.</span><button className="primary-button" disabled={busy} onClick={() => { setBusy(true); api.savePlanningScenario(scenarioName.trim(), simulation).then((saved) => { setMessage(`Saved “${saved.name}”. Your active squad was not changed.`); setConfirmSave(false); }).catch((error) => setMessage(error instanceof Error ? error.message : 'Could not save scenario.')).finally(() => setBusy(false)); }}>Confirm save</button><button className="text-button" onClick={() => setConfirmSave(false)}>Cancel</button></div> : <button className="secondary-button" disabled={busy || !scenarioName.trim()} onClick={() => setConfirmSave(true)}>Save to planning</button>}</div></article>}
  </div>;
}

function Metric({ label, value, warning = false }: { label: string; value: string; warning?: boolean }) { return <div><span>{label}</span><strong className={warning ? 'warn' : ''}>{value}</strong></div>; }
function signed(value: number) { return `${value > 0 ? '+' : ''}${value.toFixed(2)}`; }

function FixtureTable({ seasonId, gameweek, horizon }: { seasonId: number; gameweek: number; horizon: number }) {
  const [items, setItems] = useState<FixtureResearchRow[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [sort, setSort] = useState<DataTableSort>({ key: 'ease', direction: 'desc' }); const [filters, setFilters] = useState<DataTableFilters>({}); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(10); const [provenance, setProvenance] = useState('');
  useEffect(() => { const controller = new AbortController(); setLoading(true); api.fixtureResearch(seasonId, gameweek, horizon, controller.signal).then((result) => { setItems(result.items); setProvenance(`${result.formulaVersion} · ${result.state} · ${result.snapshotId}`); setError(''); }).catch((reason) => { if (!controller.signal.aborted) setError(reason instanceof Error ? reason.message : 'Fixture research is unavailable.'); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [seasonId, gameweek, horizon]);
  const rows = useMemo(() => localRows(items.filter((row) => !filters.team || row.team.name.toLowerCase().includes(filters.team.toLowerCase())), sort, page, pageSize, { ease: (row) => row.ease, fixtures: (row) => row.fixtureCount, team: (row) => row.team.name }), [items, filters, sort, page, pageSize]);
  const columns: DataTableColumn<FixtureResearchRow>[] = [{ id: 'team', header: 'Club', sortKey: 'team', filter: { type: 'text', id: 'team', label: 'Filter clubs' }, cell: (row) => <strong>{row.team.name}</strong> }, { id: 'ease', header: 'Ease', sortKey: 'ease', defaultSortDirection: 'desc', cell: (row) => <span className="value-pill">{row.ease.toFixed(2)}</span> }, { id: 'fixtures', header: 'Fixtures', sortKey: 'fixtures', defaultSortDirection: 'desc', cell: (row) => row.fixtureCount }, { id: 'blanks', header: 'Blanks', cell: (row) => row.blankGameweeks.join(', ') || '—' }, { id: 'doubles', header: 'Doubles', cell: (row) => row.doubleGameweeks.join(', ') || '—' }, { id: 'run', header: 'Run', cell: (row) => row.fixtures.map((fixture) => `GW${fixture.gameweek} ${fixture.homeTeam === row.team.id ? 'H' : 'A'}`).join(' · ') || 'No fixture' }];
  return <><p className="formula-provenance">{provenance}</p><DataTable caption="Fixture swing rankings" testId="fixture-table" columns={columns} rows={rows.rows} rowKey={(row) => row.team.id} sort={sort} filters={filters} loading={loading} error={error} onSortChange={(next) => { setSort(next); setPage(1); }} onFilterChange={(id, value) => { setFilters({ ...filters, [id]: value }); setPage(1); }} onClearFilters={() => setFilters({})} page={page} pageSize={pageSize} total={rows.total} onPageChange={setPage} onPageSizeChange={(value) => { setPageSize(value); setPage(1); }} /></>;
}

function DifferentialTable({ seasonId, gameweek, horizon }: { seasonId: number; gameweek: number; horizon: number }) {
  const [items, setItems] = useState<DifferentialRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [sort, setSort] = useState<DataTableSort>({ key: 'score', direction: 'desc' });
  const [filters, setFilters] = useState<DataTableFilters>({});
  const [position, setPosition] = useState(0);
  const [maxPrice, setMaxPrice] = useState(0);
  const [maxOwnership, setMaxOwnership] = useState(10);
  const [minMinutes, setMinMinutes] = useState(180);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const [notice, setNotice] = useState('');
  useEffect(() => {
    const controller = new AbortController();
    setLoading(true);
    api.differentials(seasonId, gameweek, horizon, { position: position || undefined, maxPrice: maxPrice || undefined, maxOwnership, minMinutes, limit: 50 }, controller.signal).then((result) => {
      setItems(result.items);
      setNotice(`${result.researchNotice} ${result.formulaVersion} · ${result.state} · ${result.snapshotId}`);
      setError('');
    }).catch((reason) => { if (!controller.signal.aborted) setError(reason instanceof Error ? reason.message : 'Differential research is unavailable.'); }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [seasonId, gameweek, horizon, position, maxPrice, maxOwnership, minMinutes]);
  const filtered = items.filter((row) => !filters.name || row.player.webName.toLowerCase().includes(filters.name.toLowerCase()));
  const rows = useMemo(() => localRows(filtered, sort, page, pageSize, { score: (row) => row.score, price: (row) => row.player.price, ownership: (row) => row.player.selectedByPercent ?? 0, points90: (row) => row.components.pointsPer90 }), [filtered, sort, page, pageSize]);
  const columns: DataTableColumn<DifferentialRow>[] = [{ id: 'player', header: 'Player', filter: { type: 'text', id: 'name', label: 'Filter players' }, cell: (row) => <span className="player-cell"><span><strong>{row.player.webName}</strong><small>{row.team.shortName}</small></span></span> }, { id: 'position', header: 'Pos', cell: (row) => positionName(row.player.position) }, { id: 'price', header: 'Price', sortKey: 'price', cell: (row) => `£${row.player.price.toFixed(1)}` }, { id: 'score', header: 'Score', sortKey: 'score', defaultSortDirection: 'desc', cell: (row) => <span className="value-pill">{row.score.toFixed(2)}</span> }, { id: 'points90', header: 'Pts/90', sortKey: 'points90', defaultSortDirection: 'desc', cell: (row) => row.components.pointsPer90.toFixed(1) }, { id: 'ownership', header: 'Owned', sortKey: 'ownership', cell: (row) => `${(row.player.selectedByPercent ?? 0).toFixed(1)}%` }, { id: 'availability', header: 'Availability', cell: (row) => <span className="availability">{row.components.availability === 1 ? 'Available' : row.components.availability === 0 ? 'Unavailable' : 'Doubtful / unknown'}</span> }, { id: 'why', header: 'Why', cell: (row) => row.explanation }];
  return <><div className="differential-controls"><label>Position<select aria-label="Differential position" value={position} onChange={(event) => { setPosition(Number(event.target.value)); setPage(1); }}><option value="0">All</option><option value="1">GK</option><option value="2">DEF</option><option value="3">MID</option><option value="4">FWD</option></select></label><label>Maximum price<input aria-label="Differential maximum price" type="number" min="0" step=".1" value={maxPrice || ''} placeholder="Any" onChange={(event) => { setMaxPrice(Number(event.target.value)); setPage(1); }} /></label><label>Maximum ownership<input aria-label="Differential maximum ownership" type="number" min="0" max="100" step=".1" value={maxOwnership} onChange={(event) => { setMaxOwnership(Number(event.target.value)); setPage(1); }} /></label><label>Minimum minutes<input aria-label="Differential minimum minutes" type="number" min="180" step="90" value={minMinutes} onChange={(event) => { setMinMinutes(Math.max(180, Number(event.target.value))); setPage(1); }} /></label></div><p className="formula-provenance">{notice}</p><DataTable caption="Differential opportunities" testId="differential-table" columns={columns} rows={rows.rows} rowKey={(row) => row.player.id} sort={sort} filters={filters} loading={loading} error={error} onSortChange={(next) => { setSort(next); setPage(1); }} onFilterChange={(id, value) => { setFilters({ ...filters, [id]: value }); setPage(1); }} onClearFilters={() => setFilters({})} page={page} pageSize={pageSize} total={rows.total} onPageChange={setPage} onPageSizeChange={(value) => { setPageSize(value); setPage(1); }} /></>;
}

function localRows<T>(items: T[], sort: DataTableSort, page: number, pageSize: number, accessors: Record<string, (row: T) => string | number>) { const accessor = accessors[sort.key]; const sorted = [...items]; if (accessor) sorted.sort((left, right) => { const a = accessor(left), b = accessor(right); const order = typeof a === 'number' && typeof b === 'number' ? a - b : String(a).localeCompare(String(b)); return sort.direction === 'asc' ? order : -order; }); const start = (page - 1) * pageSize; return { rows: sorted.slice(start, start + pageSize), total: sorted.length }; }
